// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegionsTask.Context;

namespace RegionsTask.Migrations
{
    [DbContext(typeof(RegionsTaskContext))]
    [Migration("20210923084854_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegionsTask.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("324c6b2c-cdec-4c8d-bc21-4fe0cdad00c8"),
                            Code = "001",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("ff6cbbb8-87c6-4d33-a909-bf6781ad054a"),
                            Code = "0011",
                            Name = "Region 2"
                        },
                        new
                        {
                            Id = new Guid("8c8648e6-b2e1-4b66-9c57-9d94ad959b0e"),
                            Code = "0012",
                            Name = "Region 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
